#!/usr/bin/env bash
# This script lists the content of the current directory, showing only the part of the name after the first dash.
for file in *; do
   if [[ "$file" == .* ]]; then
   continue
   fi
  name_part=$(echo "$file" | cut -d '-' -f 2-)
  echo "$name_part"
done
